/**
 * Structural diff between two graph version documents (Req 8.4 — version
 * history "with structural diff summaries"). Pure and DB-free; joins on the
 * STABLE node/edge ids (Req 1.5), which is exactly why those ids must never
 * be regenerated by the editor (P15).
 *
 * Layout is deliberately ignored: moving a node on the canvas is not a
 * structural change. Publish-time exemplar embeddings are ignored too — they
 * are derived data recomputed each publish, not authored structure.
 */

import type { GraphDocument, GraphNode, GraphEdge } from '@/lib/ai/engine/types';

export interface GraphDiffEntry {
  id: string;
  /** Node name / edge condition summary at the newer side (or older, for removals). */
  label: string;
  change: 'added' | 'removed' | 'changed';
}

export interface GraphDiff {
  nodes: GraphDiffEntry[];
  edges: GraphDiffEntry[];
  /** True when nothing structural changed (labels/layout-only edits). */
  identical: boolean;
}

/** Stable stringify with sorted keys so property order never fakes a change. */
function stableStringify(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(stableStringify).join(',')}]`;
  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return `{${entries.map(([k, v]) => `${JSON.stringify(k)}:${stableStringify(v)}`).join(',')}}`;
}

function edgeLabel(edge: GraphEdge, nodesById: Map<string, GraphNode>): string {
  const from = nodesById.get(edge.from)?.name ?? edge.from;
  const to = nodesById.get(edge.to)?.name ?? edge.to;
  return `${from} → ${to} (${edge.condition.type})`;
}

export function diffGraphDocuments(older: GraphDocument, newer: GraphDocument): GraphDiff {
  const nodes: GraphDiffEntry[] = [];
  const edges: GraphDiffEntry[] = [];

  const oldNodes = new Map(older.nodes.map((n) => [n.id, n]));
  const newNodes = new Map(newer.nodes.map((n) => [n.id, n]));
  for (const [id, node] of newNodes) {
    const prev = oldNodes.get(id);
    if (!prev) nodes.push({ id, label: node.name, change: 'added' });
    else if (stableStringify(prev) !== stableStringify(node)) nodes.push({ id, label: node.name, change: 'changed' });
  }
  for (const [id, node] of oldNodes) {
    if (!newNodes.has(id)) nodes.push({ id, label: node.name, change: 'removed' });
  }

  const oldEdges = new Map(older.edges.map((e) => [e.id, e]));
  const newEdges = new Map(newer.edges.map((e) => [e.id, e]));
  for (const [id, edge] of newEdges) {
    const prev = oldEdges.get(id);
    if (!prev) edges.push({ id, label: edgeLabel(edge, newNodes), change: 'added' });
    else if (stableStringify(prev) !== stableStringify(edge)) edges.push({ id, label: edgeLabel(edge, newNodes), change: 'changed' });
  }
  for (const [id, edge] of oldEdges) {
    if (!newEdges.has(id)) edges.push({ id, label: edgeLabel(edge, oldNodes), change: 'removed' });
  }

  return { nodes, edges, identical: nodes.length === 0 && edges.length === 0 };
}
