/**
 * Client-safe helpers for the graph editor (Block D2).
 *
 * Ids are minted ONCE at creation and never regenerated by layout, copy, or
 * re-import — telemetry and annotations join on them (Req 1.5 / P15).
 * Condition summaries are the human-readable canvas labels (Req 8.3).
 */

import type { EdgeCondition, GraphDocument, GraphEdge, GraphNode } from '@/lib/ai/engine/types';

export const newNodeId = () => `n_${crypto.randomUUID().slice(0, 13)}`;
export const newEdgeId = () => `e_${crypto.randomUUID().slice(0, 13)}`;
export const newChipId = () => `chip_${crypto.randomUUID().slice(0, 8)}`;

export const CONDITION_TYPES: EdgeCondition['type'][] = [
  'intent',
  'pattern',
  'tool_result',
  'ui_state',
  'chip',
  'slot',
  'turn_quality',
  'probe',
  'pivot',
  'always',
];

/** Human-readable condition summary rendered on the canvas (Req 8.3). */
export function summarizeCondition(condition: EdgeCondition): string {
  switch (condition.type) {
    case 'intent':
      return `intent: ${condition.exemplars[0] ?? '…'}${condition.exemplars.length > 1 ? ` (+${condition.exemplars.length - 1})` : ''}`;
    case 'pattern':
      return `pattern: ${condition.anyOf.slice(0, 2).join(' | ')}${condition.anyOf.length > 2 ? ' …' : ''}`;
    case 'tool_result':
      return `tool ${condition.tool} ${condition.predicate.op} ${condition.predicate.path}`;
    case 'ui_state':
      return `ui: ${condition.event}${condition.match ? ` ~ ${condition.match}` : ''}`;
    case 'chip':
      return `chip tap: ${condition.chipId}`;
    case 'slot':
      return `slot ${condition.name} ${condition.op}${condition.value ? ` "${condition.value}"` : ''}`;
    case 'turn_quality':
      return `${condition.consecutiveLowEffort}+ low-effort turns`;
    case 'probe':
      return 'probe detected';
    case 'pivot':
      return 'topic pivot';
    case 'always':
      return 'always (start chain)';
  }
}

/** Sensible starting params when the owner switches an edge's condition type. */
export function conditionDefaults(type: EdgeCondition['type']): EdgeCondition {
  switch (type) {
    case 'intent':
      return { type, exemplars: [] };
    case 'pattern':
      return { type, anyOf: [] };
    case 'tool_result':
      return { type, tool: '', predicate: { path: '', op: 'exists' } };
    case 'ui_state':
      return { type, event: 'project_opened' };
    case 'chip':
      return { type, chipId: '' };
    case 'slot':
      return { type, name: '', op: 'filled' };
    case 'turn_quality':
      return { type, consecutiveLowEffort: 3 };
    case 'probe':
    case 'pivot':
    case 'always':
      return { type };
  }
}

export function makeNode(partial?: Partial<GraphNode>): GraphNode {
  return {
    id: newNodeId(),
    name: 'New node',
    role: 'state',
    guidance: { promptFragments: [] },
    contextSet: [],
    ...partial,
  };
}

export function makeEdge(from: string, to: string): GraphEdge {
  return {
    id: newEdgeId(),
    from,
    to,
    priority: 100,
    condition: conditionDefaults('pattern'),
    purge: 'replace',
  };
}

/** Node ids that declare each slot name — for edge slot-condition pickers and P21 hints. */
export function declaredSlotNames(document: GraphDocument): string[] {
  return [...new Set(document.nodes.flatMap((n) => n.slots?.capture.map((c) => c.name) ?? []))];
}

export interface EditorMeta {
  tools: Array<{ name: string; description: string; executionContext: string }>;
  aliases: string[];
  voiceClipCategories: string[];
  entities: Array<{ id: string; entityType: string; slug: string; title: string | null }>;
}

/** Multiline textarea <-> string[] helpers (one entry per line). */
export const linesToArray = (text: string): string[] =>
  text
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);
export const arrayToLines = (arr: string[] | undefined): string => (arr ?? []).join('\n');
