/**
 * Seed article content (2026-07-17 deep-content rewrite, ai-assistant 7.21).
 *
 * The owner tests retrieval, chunking of long paragraphs, multi-topic context
 * management, and the think_harder escalation against these articles — so
 * they carry REAL depth, not lorem-ipsum feature lists:
 *
 *  - portfolio-website: the actual system this repo implements, described
 *    truthfully (voice pipeline, T0–T3 retrieval, engine, cost governance).
 *  - llm-systems-research: a genuine research notebook on modern LLM systems
 *    (owner ask: "something I will automatically learn while testing").
 *  - e-commerce-platform: the same sample domain, rewritten at real
 *    engineering depth (payments, inventory concurrency, checkout sagas).
 *
 * Format contract with prisma/seed.ts's convertToTiptapJSON: blocks split on
 * blank lines; '#'/'##'/'###' headings (headings become T2 anchors — keep
 * them distinctive and stable); '- ' bullet blocks; long prose paragraphs
 * (the point — they become substantial T3 chunks). No tables, no '---', no
 * markdown links, no code fences (the converter's handling of those is poor).
 *
 * KEEP the e-commerce 'Results and Business Impact' heading — historical
 * drills (6.12/6.14) target that anchor.
 */

export const PORTFOLIO_ARTICLE = `# This Portfolio — an AI-Narrated Website

The website you are reading this on is itself the flagship project. It is a Next.js portfolio whose defining feature is a conversational AI narrator: a visitor can talk to the site — literally, over voice — and the assistant answers from a semantic index of everything published here, navigates the page while speaking, and hands the hardest questions to a stronger reasoning model. Everything described below is running in this repository right now, and the assistant answering your questions is grounded in this very article, which makes it a rare artifact: documentation that can be interrogated by the system it documents.

## Architecture at a Glance

The stack is deliberately boring where it can afford to be and unusual only where the product demands it. The frontend is Next.js App Router with React and Tailwind; content is authored in a Tiptap rich-text editor and stored as structured JSON; the database is PostgreSQL with the pgvector extension, accessed through Prisma. The deployment target is serverless, which quietly shapes many design decisions: no long-lived in-process state can be trusted, so anything that must survive across requests — rate-limit windows, conversation state, processing-job claims — lives in Postgres rows with compare-and-set semantics rather than in memory. The unusual parts are three subsystems layered over that base: a client-direct realtime voice pipeline, a tiered retrieval index, and a node-graph conversation engine, each of which gets its own section below.

## The Voice Pipeline

### Client-Direct Realtime Voice

The assistant's primary mode is native speech-to-speech: the browser connects directly to a realtime voice model over WebRTC, so audio never proxies through the site's own servers. The server's role is reduced to minting — a short-lived, gateway-protected endpoint assembles the system prompt, the tool definitions, and the grounding frame, exchanges the real API key for an ephemeral client secret, and hands the browser a token that is useless for anything except opening that one session. This keeps latency at the theoretical minimum (the audio path is one hop) while keeping the actual credentials strictly server-side. A second adapter speaks Gemini's live-session protocol over WebSocket with the same contract, and browser quirks are handled per-transport — Firefox, whose WebRTC stack has a known interoperability problem with one provider's media servers, is transparently routed to a WebSocket transport where the adapter does its own PCM capture, resampling, and playback scheduling.

### The Cascade Fallback and One Shared Brain

Realtime speech models are the most expensive and least steerable models in the fleet, so there is a second voice family: a cascade that runs speech-to-text, then a conventional reasoning model, then text-to-speech. The critical design rule is that the cascade's brain is the same code path that serves plain text chat — one prompt assembly, one tool registry, one retrieval chain. That rule, applied everywhere, is what keeps three runtimes (native voice, cascade voice, text) behaviorally consistent: a fix to retrieval or guidance lands in all three at once, and the test suite drives golden conversation scenarios through the real engine to pin that consistency.

### Latency as a Product Surface

Voice exposes every millisecond. The system measures per-tool median execution times from its own telemetry and injects that into the prompt as behavioral guidance: instant tools are called silently and the model narrates the result, while genuinely slow tools get a short, context-relevant spoken lead-in. Beneath that, a library of pre-recorded filler clips — matched to the session's actual voice so a Gemini session never speaks with an OpenAI voice — covers unexpected gaps, chosen by expected duration so a clip is never cut off mid-sentence by the model resuming. Even the microphone is managed against acoustics: short clips gate the mic for their duration plus an echo tail, because speaker-to-microphone bleed was measurably producing hallucinated user turns in transcripts.

## Retrieval: The T0–T3 Semantic Index

### Tiered Chunking

Every published article is decomposed into four tiers. T0 is metadata — title, technologies, one-liners. T1 is an AI-written summary of the whole piece. T2 is one chunk per section heading, and deliberately contains no full text, only budget-bounded summaries — this is the tier that keeps global, multi-project search affordable in a context window. T3 is the actual prose, chunked within heading boundaries so a chunk never straddles two topics. The heading is treated as the section's most important anchor: chunk identifiers are slugified headings, embeddings include the title alongside the body, and full-text search weights title matches three times body matches, because a visitor who asks for the results section is naming a heading, not quoting body text.

### Hybrid Retrieval and Honest Ranking

Queries run two retrieval passes in parallel: dense vector similarity over pgvector with an HNSW index, and Postgres full-text search with an OR-relaxed fallback for long spoken queries whose every word would otherwise be ANDed into oblivion. Fusion takes the maximum of the two scores plus an agreement bonus, then maximal-marginal-relevance diversification spreads results across projects — with the cap lifted for a project the query names explicitly, because naming a project is a stronger signal than any ambient context. Results carry navigation targets derived from the chunk-to-anchor contract, so the model can scroll the visitor to the exact section it is citing, and every result carries a relevance score plus a plain-language why field. Guidance then enforces honesty: a weak match is not an answer, and the model is told to say the portfolio does not cover something rather than presenting the nearest neighbor as if it did.

## Context Management Under a Tight Budget

Realtime voice models re-bill the entire conversation as input on every response, so context size times turn rate is the real cost meter, and token-per-minute rate limits are the real ceiling. The system treats the context window as a budgeted resource: a per-conversation context buffer collects keyed items from every producer — navigation state, engine directives, profile summaries — deduplicates by key with last-write-wins, and flushes one compact diff at turn boundaries instead of letting producers spray messages mid-turn. Navigation context is append-only by design because prefix-based prompt caching makes appends nearly free while any mid-history edit invalidates the cache from that point on. The floating per-turn state block was dieted from kilobytes of raw JSON to a compact orientation text, with an instant client-side tool available when the model genuinely needs the full detail of what is on screen. Long conversations prune verbatim turns into a running summary, and resumed sessions are re-briefed with that summary plus a verbatim tail — a deliberate compaction point.

## The Conversation Engine

Above the model sits a node-graph conversation engine. Authored graphs define nodes with their own context, tool allowlists, and suggestion chips; edges fire on typed conditions — visitor intent, captured slots, tool results — with priorities ordered so cheap deterministic signals outrank expensive inferred ones. A per-turn classifier grades evidence for visitor traits (technical fluency, probing, hostility, intent) on an ordinal scale rather than raw floats, because small models cannot calibrate probabilities but can rank; the host applies hysteresis thresholds over a ring of recent turns so one odd utterance never flips behavior. The same machinery captures stated facts into slots, which feed consent-gated conversions: a lead-capture tool that records who the visitor is and notifies the owner, a recruiter-only job-description intake whose submissions are analyzed against the owner's background by a reasoning model, and a client-request intake for people who want work built rather than a person hired.

## Tools Across Three Runtimes

All capabilities are declared once in a unified tool registry with an execution-context flag. Client tools run in the browser — declarative navigation, highlighting, form dictation — and their results are honest by construction: a failed navigation throws with the real error rather than being narrated over as success. Server tools run behind one gateway-wrapped execution endpoint — semantic search, content fetch, lead capture, and a think-harder escalation that hands a hard question plus retrieved grounding plus the conversation tail to a stronger reasoning model and returns a synthesized answer for the voice model to narrate. Deciding which tier of visitor may call which tool is an explicit allowlist decision per tool, and the registry is also exposed through a public MCP server, so external AI agents can query the same portfolio content through the same retrieval chain with the same visibility rules.

## Cost Governance and Access Control

Every cost-incurring route passes through a single gateway that resolves the caller's tier — anonymous public, invited reflink, or admin — and applies, in order: a global kill switch, tier policy, session validation, blacklist and windowed rate limits, and finally metering into a usage ledger with per-request attribution. Reflinks are capability grants: an invitation link carries feature flags and a spend budget, binds itself to a bounded set of client IP hashes so a leaked link cannot open premium access to the whole internet, and is drainable and revocable. A static check in the build pipeline asserts that no route matching cost-incurring patterns ships without the gateway wrapper, which turns a policy into an invariant.

## Verification Culture

The system's development rule is that a feature is not done until it has been driven end-to-end. Because voice is hard to test unattended, there is a fake-microphone harness: synthesized speech is fed into an emulated microphone track that drives the real WebRTC session, so an agent can hold an actual spoken conversation with the assistant, then read the persisted transcript rows and assert on them. Golden conversation scenarios run through the real engine against fake models in CI at zero spend. Live-fire drills with small capped budgets exercise the real pipeline on a fixture project. And the honesty rules apply to the system's own telemetry: transcripts persist what the model actually received and returned, tool rows carry real execution outcomes, and known failures are recorded as findings rather than smoothed over.

## What Testing This Site Teaches

Because the narrator is grounded in this article, the site doubles as a live laboratory: ask it how its own retrieval works and watch it search this very document; ask a question deeper than the summary tier and watch the escalation tool engage; open two projects in a row and watch the navigation context follow you. The portfolio does not claim the system is finished — the honest ledger of findings, fixes, and open follow-ups is part of the work being shown.`;

export const LLM_RESEARCH_ARTICLE = `# Modern LLM Systems — Research Notes

These are working notes on how modern large language models actually function, written for an engineer who wants the mechanisms rather than the marketing. Each section goes one level deeper than the usual summary: not just that a technique exists, but what problem forced it into existence, what it trades away, and where its numbers come from. The sections are self-contained on purpose — this document is also a test corpus for retrieval over long, multi-topic articles — but they build toward one theme: nearly everything in modern LLM engineering is a negotiation between memory bandwidth, compute, and data.

## Attention and the Transformer Core

At the heart of a transformer is a deceptively simple operation. Each token's representation is projected into three vectors — a query, a key, and a value. A token's query is dotted against every previous token's key, the scores are scaled and softmaxed into weights, and those weights average the previous tokens' values into a fresh representation. That is attention: a learned, content-addressed lookup over everything already written. Stacking dozens of such layers, each with dozens of independent heads attending to different relational patterns, and interleaving them with feed-forward layers that do per-token computation, yields the whole architecture. The causal mask — each token may only attend backward — is what makes the same network a generator: at inference you feed what exists and sample what comes next, one token at a time. The quadratic cost everyone cites comes from that all-pairs dot product: doubling sequence length quadruples the attention compute in the prefill phase.

### The KV Cache and Its Memory Bill

Generation would be intolerably slow if every new token recomputed keys and values for the entire history, so inference engines cache them: the KV cache. The consequence is that autoregressive decoding is not compute-bound but memory-bandwidth-bound — for every generated token, the accelerator must stream the whole cache through its memory system to compute attention against it. The arithmetic is worth internalizing. Cache size scales as two vectors per token, per layer, per attention head: for a model with dozens of layers and a hidden size in the thousands, a single long conversation at 16-bit precision occupies gigabytes, and that memory is per-request — it cannot be shared across concurrent users the way weights can. This one number explains a remarkable fraction of the field's engineering: why long context is expensive, why batch sizes collapse as conversations grow, and why so many architectural inventions exist purely to shrink it.

### MQA, GQA and Attention Compression

The first family of fixes shrinks the cache directly. Multi-query attention keeps many query heads but shares a single key-value head among them, cutting the cache by the head count at a modest quality cost. Grouped-query attention is the compromise that stuck: query heads are partitioned into groups, each sharing one KV head, so an architecture might keep a quarter or an eighth of the original cache while matching quality closely — most production open models now ship with GQA. A more aggressive line of work compresses the cache algebraically: multi-head latent attention, introduced in the DeepSeek lineage, projects keys and values into a small shared latent vector per token and reconstructs per-head views on the fly, trading a little extra compute — which decoding has to spare — for an order-of-magnitude smaller cache. That trade is the correct direction precisely because decoding is bandwidth-bound: spending idle FLOPs to move fewer bytes is nearly free speed.

### FlashAttention and IO-Aware Kernels

The second fix accepts the math and reorganizes the memory traffic. Naive attention materializes the full score matrix in slow device memory. FlashAttention computes the same exact result in tiles that live in fast on-chip SRAM, carrying softmax running statistics so the big matrix never exists at all — same FLOPs, drastically less data movement, and in practice several times faster with sequence-length memory now linear. Its significance is bigger than one kernel: it demonstrated that the profitable optimization target in this field is bytes moved, not operations performed, and successive versions have chased each new GPU generation's memory hierarchy. The general lesson — count memory traffic first — is the single most transferable idea in LLM systems work.

## Scaling Laws and the Economics of Training

Language model quality improves as a smooth power law in parameters, data, and compute, which is why the field can plan around scale at all. The original scaling-law work concluded that model size should grow much faster than data, and the first wave of giant models was trained accordingly — huge, and undertrained. The Chinchilla revision fixed the accounting: at fixed compute, loss is minimized by scaling parameters and training tokens roughly together, with a rule of thumb near twenty tokens per parameter. A seventy-billion-parameter model trained on far more data outperformed much larger predecessors at the same budget, and the field re-planned around data.

### Inference-Aware Scaling

Chinchilla optimizes the wrong objective for anyone who serves models. It minimizes training loss per training dollar, but a deployed model's lifetime cost is dominated by inference, and inference cost scales with model size while being indifferent to how many tokens the model was trained on. So the modern practice is deliberate over-training: take a small model and push it far past its Chinchilla-optimal data budget — hundreds of tokens per parameter — accepting diminishing training-side returns to buy a cheaper, faster model at serving time. The strongest small open models are trained on token counts that would have looked absurd under the original prescriptions. The deeper issue behind all of this is that data, not compute, is becoming the binding constraint: the supply of high-quality text is finite, which pushes the frontier toward synthetic data pipelines, aggressive filtering and deduplication, and multiple epochs over the best sources — each with its own quality cliffs.

## Long Context

### Rotary Positions and Context Extension

Most modern models encode position with rotary embeddings: each query and key vector is rotated by an angle proportional to its absolute position, at a spectrum of frequencies, which makes attention scores depend only on relative distance. The elegance has a cost — a model trained to a fixed length has never seen larger rotation angles, and extrapolating past them shatters attention. Context-extension methods rescale rather than extrapolate: position interpolation compresses new, longer positions into the trained angular range and fine-tunes briefly; NTK-aware scaling and YaRN refine this by rescaling frequency bands unevenly, preserving the high-frequency components that encode fine local order while stretching the low-frequency ones that encode coarse global position. These methods took open models from four-thousand-token windows to hundreds of thousands with modest additional training.

### Attention Sinks and Streaming

A strange empirical fact: transformers dump large attention mass onto the first few tokens regardless of their content. Softmax must put its probability somewhere, and models learn to use early tokens as a garbage collector for attention that has no better target. This matters operationally — if a sliding-window deployment evicts those earliest tokens from the cache, generation quality collapses. Streaming setups therefore pin a handful of sink tokens permanently in the cache and slide the window over everything else, which stabilizes indefinitely long sessions with a bounded cache.

### A Long Window Is Not Memory

The most practically important long-context finding is behavioral: models retrieve information best from the beginning and end of the window, and reliably worse from the middle — the lost-in-the-middle effect. A million-token window that has been mostly filled behaves less like a database and more like a tired reader. Effective-context benchmarks that require multi-hop use of mid-window facts show much smaller usable capacities than advertised maxima. The engineering consequence is that context placement is part of prompt design — instructions and the most load-bearing evidence belong at the edges — and that retrieval remains necessary even when everything technically fits, because a focused window of relevant text beats a diluted window of everything. Long context and retrieval are complements, not competitors.

## Post-Training: From Base Model to Assistant

### Supervised Fine-Tuning and RLHF

A pretrained base model is a text-completion engine with no preference for being helpful. Post-training installs the assistant. Supervised fine-tuning on demonstration conversations teaches format and instruction-following quickly — the consensus is that SFT mostly unlocks and styles capabilities that pretraining already built. Reinforcement learning from human feedback then optimizes for preference: annotators rank pairs of responses, a reward model is trained to predict those rankings, and the policy is optimized — classically with PPO — to maximize predicted reward under a KL-divergence penalty that tethers it to its starting point. The KL penalty is not a detail; it is the load-bearing safeguard. The reward model is only a proxy, and unconstrained optimization against a proxy invites reward hacking — the policy discovers that length, confidence, sycophancy, or format flourishes raise predicted reward without raising quality. Goodhart's law, operationalized.

### Direct Preference Optimization and Its Family

RLHF's machinery is heavy: a separate reward model, online sampling, notorious training instability. Direct preference optimization collapsed the pipeline with one derivation — under the KL-regularized objective, the optimal policy has a closed form in which the reward is expressible through the policy's own log-probabilities, so you can train directly on preference pairs with a simple classification-style loss. No reward model, no rollouts. In exchange you lose the online loop: DPO fits the preferences you collected, while RL can explore beyond them. Variants adjust the trade — KTO learns from unpaired thumbs-up or thumbs-down signals, ORPO folds preference pressure into the SFT pass itself. Production pipelines are typically staged hybrids, and RLAIF replaces much of the human labeling with AI feedback guided by a written constitution — the critical scaling move, since human annotation is the scarcest input in the pipeline.

### Reasoning Models and Test-Time Compute

The most consequential recent shift is training models to think longer instead of only training them bigger. The ingredients: chain-of-thought as a substrate, process reward models that score each reasoning step rather than only the final answer — which materially improves math and code reliability, since outcome-only rewards credit lucky wrong reasoning — and reinforcement learning against verifiable objectives like test suites and checkable answers, where the reward cannot be sweet-talked. Verifiability is the quiet key: it is why reasoning training concentrated first in math and code. The DeepSeek-R1 recipe demonstrated that large-scale RL with a simple, efficient policy-gradient method (GRPO, which normalizes rewards across groups of sampled solutions instead of training a value model) can elicit long, self-correcting reasoning chains — including emergent backtracking — and that those behaviors distill surprisingly well into small models via plain supervised fine-tuning on reasoning traces. The systems-level reading: test-time compute is a new scaling axis. A model that can spend variable thinking tokens turns inference cost into a quality dial, and serving infrastructure now has to price and schedule thought.

## Efficient Inference

### Quantization

Weights train in sixteen bits but do not need them to be served. Post-training quantization to eight bits is essentially free; four bits is the practical sweet spot for weight-only quantization, roughly quartering memory and, because decoding is bandwidth-bound, speeding it up nearly proportionally. The obstacle is outliers — rare, systematically large activation channels that explode naive quantization error. The methods that work treat them asymmetrically: GPTQ quantizes weights column-by-column while correcting residual error against a calibration set, and AWQ observes that a tiny fraction of weight channels — those multiplying large activations — carry disproportionate importance and protects them via per-channel scaling. Below four bits, quality degrades sharply without quantization-aware training. The KV cache itself is also quantized in production, which composes with GQA and latent attention: every cache byte saved is decode speed earned.

### Speculative Decoding

Decoding wastes the accelerator: one token per full forward pass. Speculative decoding exploits the asymmetry that verifying tokens is parallel while generating them is serial. A small draft model proposes several tokens; the large model scores them all in one pass; a rejection-sampling rule accepts the longest prefix consistent with the large model's distribution and resamples at the first divergence. The output distribution is provably identical to the large model decoding alone — this is a pure latency trick with no quality trade — and acceptance rates on natural text commonly yield two-to-three-fold speedups. Later variants eliminate the separate draft model by giving the base model lightweight extra decoding heads that predict several tokens ahead, in the style of Medusa and EAGLE.

### Continuous Batching and Paged Memory

Serving throughput was historically murdered by static batching: requests batched together had to finish together, so short requests idled behind long ones. Continuous batching schedules at the iteration level, admitting and retiring requests every decoding step. Its enabling insight was a memory-management one — vLLM's PagedAttention allocates the KV cache in fixed-size blocks with an indirection table, exactly like virtual memory pages, eliminating the fragmentation that contiguous per-request allocations caused and allowing shared prefixes (the system prompt every request carries) to be stored once via copy-on-write. Prefix caching at the serving layer is the same idea stretched across requests, and it is why append-only prompt construction is a real cost optimization: any edit to an earlier position invalidates the reusable prefix from that point on.

## Mixture-of-Experts

MoE decouples a model's knowledge capacity from its per-token compute. The feed-forward block — most of a transformer's parameters — is replicated into many experts, and a learned router sends each token to its top one or two. Total parameters can reach the hundreds of billions while active parameters per token stay at a fraction of that, and the scaling-law benefit is real: at equal training compute, sparse models beat dense ones on loss. The costs are systems costs. All experts must sit in memory even though few fire per token, so MoE buys compute efficiency with memory hunger. Routing must be balanced — an unregularized router collapses onto favorite experts, starving the rest — so training adds load-balancing auxiliary losses, or, in the aux-loss-free approach of DeepSeek-V3, per-expert bias terms adjusted online to steer traffic without distorting the main objective. At datacenter scale experts shard across devices and every MoE layer becomes an all-to-all communication event, which is why MoE efficiency claims must always be read jointly with interconnect assumptions. Fine-grained experts plus a small set of always-on shared experts is the current sweet spot.

## Retrieval-Augmented Generation Done Properly

RAG bolts an external memory onto a frozen model: embed a corpus into vectors, retrieve nearest neighbors for a query, and place them in context. Done naively it disappoints, and the failure points are always the same three. Chunking: fixed-size windows sever sentences from their referents, so production systems chunk along document structure — headings, sections, paragraphs — attach titles and metadata to each chunk, and often index summaries hierarchically above raw text so a query can land coarsely and drill in. Retrieval itself: dense embeddings capture paraphrase but miss exact identifiers and rare terms, lexical search has the opposite failure profile, and hybrid retrieval with score fusion beats either alone almost universally; a cross-encoder reranker over the top candidates buys precision that single-vector search structurally cannot express. And grounding behavior: the model must be instructed and evaluated to answer from evidence, cite it, and decline when evidence is absent — retrieval quality means nothing if generation freelances anyway. Evaluation decomposes the pipeline: retrieval recall, answer faithfulness to the provided context, and answer relevance are separate numbers with different fixes. The recurring judgment call is retrieval versus fine-tuning, and the working rule is that fine-tuning teaches form — style, format, procedure — while retrieval supplies facts, because facts held in weights go stale and cannot be audited, while facts in an index are updatable, inspectable, and per-user accessible. Long context has not killed RAG; it has upgraded RAG's job from squeezing text into a small window to curating a relevant, well-ordered working set for a large one.

## State-Space Models and Hybrids

Attention's cache grows linearly and its prefill quadratically, which keeps the door open for architectures with constant-size state. Modern state-space models like Mamba maintain a fixed-size recurrent state and process sequences in linear time; Mamba's contribution was making the state dynamics input-dependent — selective — so the model can gate what to remember or forget, recovering much of the content-addressability that made attention win in the first place, with hardware-friendly scan algorithms to keep it fast. Pure SSMs still trail transformers at exact long-range recall, which is intuitive: a constant-size state must lossily compress an unbounded past, while a KV cache is a lossless transcript. The pragmatic answer is hybridization — interleaving a small number of attention layers into a mostly-SSM stack, as in Jamba-style architectures, retains near-transformer quality with a fraction of the cache. Reading these designs as cache-compression strategies rather than transformer replacements is the clearer lens, and the direction matters most wherever memory is the binding constraint: long documents, streaming audio, on-device inference.

## Evaluation and Failure Modes

Evaluation is the weakest link in the whole stack. Static benchmarks decay on contact with the internet: once test items circulate in pretraining data, scores measure memorization — contamination — and several celebrated results have shrunk under contamination audits. Multiple-choice accuracy saturates and rewards test-taking heuristics; human preference arenas measure something real but conflate quality with confidence, verbosity, and formatting; LLM-as-judge scales cheaply but imports the judge's biases — self-preference among them — and must itself be validated against human judgment on a sample before its scores mean anything. Hallucination, the signature failure, is not one defect but a family: fabrication when the model lacks the fact, unfaithfulness when it contradicts context it was given, and reasoning errors that draw wrong conclusions from correct premises — each with different mitigations, from retrieval grounding to entailment-checked generation to verifier-guided decoding. The competence to build is evaluation engineering: private held-out sets aligned with the actual product task, judge pipelines audited against humans, and the discipline to distrust any single number.

## Where This Is Heading

Three trajectories organize the near future. Test-time compute makes intelligence elastic: quality becomes a function of tokens spent thinking, so routing — deciding per query how much model and how much thought to buy — becomes a first-class serving problem. Agentic operation replaces single answers with tool-using episodes, which moves the difficulty from fluency to reliability: a small per-step error rate compounds brutally across a long action chain, so verification, checkpointing, and honest failure reporting matter more than eloquence. And the efficiency frontier — quantization, sparsity, distillation, cache compression, hybrid architectures — keeps translating any fixed capability level onto cheaper hardware, which is what ultimately decides where models run and who can run them. The through-line of all three is the same negotiation these notes opened with: memory, compute, and data, traded against each other under a latency budget.`;

export const ECOMMERCE_ARTICLE = `# E-commerce Platform

A full-featured e-commerce build serving a catalog of tens of thousands of SKUs, examined here at engineering depth. The interesting parts of commerce software are not the product grid and the cart icon — they are the places where money, concurrency, and third-party systems collide: charging a card exactly once on a flaky network, not selling the same last unit twice, and keeping a checkout pipeline honest when any step can fail mid-flight. This article walks the architecture through those pressure points.

## Business Context

The platform serves a mid-sized retailer with complex products — apparel with size and color matrices, bundles, regional pricing, and periodic flash sales that concentrate a week of traffic into an hour. Those flash sales set the engineering bar: the system's worst hour, not its average day, defines the design. Requirements that shaped everything downstream: no oversells on limited inventory, no double charges under any retry scenario, checkout availability during traffic spikes even if noncritical features degrade, and a financial audit trail that reconciles to the cent against the payment provider's records.

## Modeling the Catalog

The catalog's core tension is that products are simultaneously marketing objects (rich copy, media, SEO slugs) and operational objects (SKUs, stock, weights, tax classes). The model separates a product — the marketing entity — from its variants, the sellable SKUs generated by option combinations like size and color. Attribute storage is the classic decision: a rigid relational schema per category is unmaintainable across a diverse catalog, while a fully generic entity-attribute-value design turns every query into a self-join festival and defeats indexing. The pragmatic middle chosen here: stable, queryable fields (price, stock, brand, category) as real columns, and a JSONB attributes document per variant with GIN indexes for the long tail — filterable facets get promoted to columns the moment they become popular filter dimensions. Category trees use a materialized-path pattern rather than adjacency lists, so a subtree query is a prefix match instead of a recursive walk.

## Inventory and the Oversell Problem

Inventory is where naive designs die in production. Reading a stock count, checking it in application code, and decrementing it is a race: two concurrent checkouts both read one-remaining and both succeed. The fix has to live in the database. Every decrement runs as a single conditional update — subtract the quantity only where available stock is still sufficient — and a zero-rows-affected result IS the out-of-stock signal, surfaced to the shopper as honestly as a missing page. Between add-to-cart and payment there is a reservation: adding a limited item places a time-boxed hold row rather than decrementing stock, a background sweeper releases expired holds, and the checkout converts holds to real decrements atomically with order creation. The hold duration is a product decision disguised as an engineering one — too short frustrates slow shoppers, too long lets carts hoard scarce stock during exactly the flash sales that need velocity. Physical-world corrections (damaged goods, miscounts, returns) never touch the stock number directly; they append signed adjustment entries, so current stock is an auditable sum rather than a mutable opinion.

## Payments in Depth

### Idempotency and the Double-Charge Problem

Networks fail after the money moves: a charge request times out, the client retries, and without protection the customer pays twice. Every money-moving call therefore carries an idempotency key — a unique token per logical attempt, stored with the outcome, so a retry with the same key returns the recorded result instead of executing again. The key must be minted when the INTENT is created (one key per checkout confirmation, not per HTTP attempt) and must survive client restarts, which means it lives in the order row, not in browser memory. The same discipline applies internally: order-creation and fulfillment-dispatch endpoints are idempotent on order identifiers, because queues deliver at-least-once and retried jobs are a certainty, not an edge case.

### Webhooks and Reconciliation

The payment provider's webhook — not the synchronous API response — is the source of truth for payment state, because the synchronous path can succeed provider-side after failing client-side. Webhook handling follows three rules learned industry-wide: verify signatures before trusting anything, treat deliveries as at-least-once and possibly out-of-order (an event for a stale state transition must be ignored gracefully), and record every accepted event in a processed-events table keyed by event identifier so redeliveries are no-ops. Beneath the integration sits a small double-entry ledger: every financial fact — authorization, capture, refund, fee, chargeback — is a balanced pair of entries in append-only accounts. Nightly reconciliation walks the provider's settlement reports against the internal ledger and alerts on any drift; the ledger is what turns a we-think-we-charged system into one that can prove what happened.

### Authorization Flows, SCA and Tokenization

Card data never touches the platform's servers: the provider's hosted fields tokenize in the browser, keeping the system out of most of PCI DSS scope, and stored payment methods are provider tokens bound to customer records. The charge flow separates authorization from capture — authorize at order placement, capture at fulfillment — which makes cancellations free and partial shipments natural. European traffic adds strong customer authentication: 3-D Secure challenges can interrupt the flow at the provider's discretion, so checkout is built as a state machine that can suspend at requires-action, hand control to the bank's challenge, and resume on the webhook — one more reason the webhook, not the redirect, drives state.

## Checkout as a Distributed Transaction

A checkout spans inventory, payment, order records, and email — systems that cannot share one database transaction. The platform treats checkout as a saga: a sequence of local steps, each with a compensating action, driven by a persisted state machine per order. Reserve inventory; authorize payment; create the order; on any failure, run the compensations in reverse (void the authorization, release the holds) and land the order in a terminal failed state that support staff can read, not a half-committed mystery. Reliability of the follow-on effects uses the transactional outbox pattern: the order commit and an outbox row are written in one database transaction, and a relay publishes outbox rows to the queue afterward — closing the gap where a service commits locally and crashes before telling anyone. Consumers are idempotent, completing the at-least-once contract end to end.

## Search and Discovery

Catalog search runs on an inverted-index engine fed by change-data events from the primary database, with the index treated as a disposable projection — rebuildable from scratch, never authoritative. Query handling layers language analysis (stemming, synonyms curated from zero-result logs), typo tolerance, and field-weighted matching where product titles dominate description text. Facet counts are computed against the filtered result set so shoppers never click into an empty combination. Ranking blends lexical relevance with business signals — availability first, then margin-aware boosts and sales velocity — and the zero-results page is instrumented as a first-class funnel: those queries are the merchandising team's demand signal for what the catalog is missing. Autocomplete runs against a separate lightweight index of names and categories with aggressive prefix matching, because its latency budget is keystroke-scale.

## Performance and Caching

The read path is layered like an onion. The CDN serves anonymous catalog pages with short TTLs plus stale-while-revalidate, so a cache miss refreshes in the background instead of stalling a shopper. An application-level Redis cache holds hot product data with explicit invalidation driven by the same change-data events that feed search — cache invalidation is handled as data flow, not as scattered delete calls at every write site. Cart and session state live in Redis with database write-behind for durability. The database itself splits reads to replicas with one sharp caveat learned the hard way: any read that feeds a money decision — stock checks, price at checkout — goes to the primary, because replica lag plus a flash sale equals overselling with extra steps. During peak events the system sheds load deliberately: recommendations and analytics degrade to static fallbacks, protecting the order path with what remains.

## Fraud and Abuse

Fraud defense is economics, not purity: every chargeback costs the goods, a fee, and reputation with the card networks, while every false decline costs a real customer — the model is tuned against both. The first layer is velocity rules — cards per account, accounts per device fingerprint, orders per address per hour — which are cheap and catch the clumsy majority. The second is a risk score blending signals (address-verification and CVV results, geo-distance between IP and shipping address, account age, basket composition — high-resale items skew risky) with thresholds that route orders three ways: auto-approve, step-up authentication, or manual review queue. Review outcomes feed the model back. Promo-code abuse gets the same treatment at lower stakes: single-use codes are enforced with the same conditional-update discipline as inventory, because a viral coupon is a flash sale for attackers.

## Observability and Peak Events

The observability spine is a per-order event trace: every state transition, payment event, and compensation lands in an append-only order history, so support can answer what happened to order X without an engineer spelunking logs. Dashboards watch the business invariants, not just CPU: authorization success rate, webhook lag, reservation-to-conversion ratio, oversell count (which must read zero), and ledger drift (likewise). Peak readiness is rehearsed, not hoped for — load tests replay a recorded flash-sale traffic shape against staging, chaos drills kill the payment provider's sandbox mid-checkout to verify the sagas compensate, and queue depth alarms are tuned so backpressure is visible minutes before customers feel it.

## Results and Business Impact

The platform processed over two million dollars in its first year with 99.9 percent availability through several flash-sale events. The numbers that matter most to the engineering story: zero recorded oversells since the reservation system replaced check-then-decrement, zero double charges since idempotency keys were enforced end to end, and a nightly reconciliation that has caught provider-side settlement discrepancies twice — both recovered because the internal ledger could prove the platform's version of events. Checkout conversion improved measurably after the payment state machine made 3-D Secure interruptions resumable instead of fatal, and the search zero-results feedback loop drove a double-digit reduction in dead-end queries within two quarters.`;
