/**
 * Semantic Dashboard API
 * 
 * Provides comprehensive metrics for semantic content management:
 * - Vector index health metrics
 * - Project semantic status
 * - Budget status
 * - Cost analytics
 * - Batch job status
 */

import { NextRequest, NextResponse } from 'next/server';
import { getSession } from '@/lib/auth-utils';
import { prisma } from '@/lib/prisma';
import { semanticBudgetManager } from '@/lib/content/SemanticBudgetManager';
import { getSemanticHealthMonitor } from '@/lib/content/SemanticHealthMonitor';

type HealthStatus = 'healthy' | 'no-content' | 'no-embeddings' | 'incomplete-summaries' | 'tree-invalid' | 'outdated' | 'corrupted';

interface HealthAnalysis {
  status: HealthStatus;
  details: string;
  recommendations: string[];
}

/**
 * Comprehensive project health analysis
 */
async function analyzeProjectHealth(project: any, chunks: any[]): Promise<HealthAnalysis> {
  // 1. No content at all
  if (chunks.length === 0) {
    return {
      status: 'no-content',
      details: 'No chunks found - project has not been processed',
      recommendations: ['Run initial content ingestion', 'Check if project has content to process']
    };
  }

  // 2. Analyze tier structure
  const tierCounts = chunks.reduce((acc, chunk) => {
    acc[chunk.tier] = (acc[chunk.tier] || 0) + 1;
    return acc;
  }, {} as Record<number, number>);

  const hasT0 = tierCounts[0] > 0;
  const hasT1 = tierCounts[1] > 0;
  const hasT2 = tierCounts[2] > 0;
  const hasT3 = tierCounts[3] > 0;

  // 3. Tree structure validation
  const treeIssues: string[] = [];
  
  // Check for T0 (project metadata)
  if (!hasT0) {
    treeIssues.push('Missing T0 project metadata chunk');
  } else if (tierCounts[0] > 1) {
    treeIssues.push(`Multiple T0 chunks found (${tierCounts[0]}), should be exactly 1`);
  }

  // Check for T1 (project summary)
  if (!hasT1) {
    treeIssues.push('Missing T1 project summary chunk');
  } else if (tierCounts[1] > 1) {
    treeIssues.push(`Multiple T1 chunks found (${tierCounts[1]}), should be exactly 1`);
  }

  // Validate parent-child relationships
  const orphanedChunks = chunks.filter(chunk => {
    if (chunk.tier === 0) return false; // T0 has no parent
    return !chunk.parentChunkId || !chunks.some(c => c.id === chunk.parentChunkId);
  });

  if (orphanedChunks.length > 0) {
    treeIssues.push(`${orphanedChunks.length} orphaned chunks (missing parents)`);
  }

  // Validate root chunk references
  const t0Chunk = chunks.find(c => c.tier === 0);
  const invalidRootRefs = chunks.filter(chunk => {
    return chunk.rootChunkId && chunk.rootChunkId !== t0Chunk?.id;
  });

  if (invalidRootRefs.length > 0) {
    treeIssues.push(`${invalidRootRefs.length} chunks with invalid root references`);
  }

  // If tree structure is broken
  if (treeIssues.length > 0) {
    return {
      status: 'tree-invalid',
      details: `Tree structure issues: ${treeIssues.join(', ')}`,
      recommendations: [
        'Run validation stage to fix parent-child relationships',
        'Consider regenerating the project from scratch',
        'Check for data corruption in recent operations'
      ]
    };
  }

  // 4. Check embeddings
  const chunksWithEmbeddings = chunks.filter(c => c.embeddingGeneratedAt !== null);
  const chunksWithoutEmbeddings = chunks.filter(c => c.embeddingGeneratedAt === null);

  if (chunksWithEmbeddings.length === 0) {
    return {
      status: 'no-embeddings',
      details: `All ${chunks.length} chunks missing embeddings - not searchable`,
      recommendations: ['Run embeddings stage', 'Check OpenAI API configuration', 'Verify embedding generation logs']
    };
  }

  if (chunksWithoutEmbeddings.length > 0) {
    // Check if missing embeddings are only on T0 (which is acceptable)
    const nonT0WithoutEmbeddings = chunksWithoutEmbeddings.filter(c => c.tier !== 0);
    if (nonT0WithoutEmbeddings.length > 0) {
      return {
        status: 'no-embeddings',
        details: `${nonT0WithoutEmbeddings.length} chunks missing embeddings (${chunksWithEmbeddings.length} have embeddings)`,
        recommendations: ['Run embeddings stage to complete missing embeddings', 'Check for failed embedding operations']
      };
    }
  }

  // 5. Check for incomplete summaries (but account for auto-populated content)
  const t1Chunk = chunks.find(c => c.tier === 1);
  const t2Chunks = chunks.filter(c => c.tier === 2);
  
  const incompleteSummaries: string[] = [];

  // Check T1 summary
  if (t1Chunk && (
    !t1Chunk.content || 
    t1Chunk.content.trim() === '' || 
    t1Chunk.content.includes('[TO BE GENERATED BY SUMMARIES STAGE]')
  )) {
    incompleteSummaries.push('T1 project summary');
  }

  // Check T2 summaries (but ignore auto-populated ones)
  const incompleteT2s = t2Chunks.filter(chunk => {
    const content = chunk.content || '';
    const isPlaceholder = content.includes('[TO BE GENERATED BY SUMMARIES STAGE]');
    const isEmpty = content.trim() === '';
    const isAutoPopulated = chunk.metadata && 
      typeof chunk.metadata === 'object' && 
      'autoPopulated' in chunk.metadata && 
      chunk.metadata.autoPopulated === true;
    
    // Only consider it incomplete if it's a placeholder or empty, and NOT auto-populated
    return (isPlaceholder || isEmpty) && !isAutoPopulated;
  });

  if (incompleteT2s.length > 0) {
    incompleteSummaries.push(`${incompleteT2s.length} T2 section summaries`);
  }

  if (incompleteSummaries.length > 0) {
    return {
      status: 'incomplete-summaries',
      details: `Missing summaries: ${incompleteSummaries.join(', ')}`,
      recommendations: [
        'Run summaries stage to generate missing AI summaries',
        'Check if content is below auto-population threshold',
        'Verify summary generation configuration'
      ]
    };
  }

  // 6. Check for data corruption
  const corruptionIssues: string[] = [];
  
  // Check for chunks with no content
  const emptyChunks = chunks.filter(chunk => 
    !chunk.content || chunk.content.trim() === ''
  ).filter(chunk => 
    // Exclude T0 and T1 which might legitimately be empty initially
    chunk.tier > 1
  );

  if (emptyChunks.length > 0) {
    corruptionIssues.push(`${emptyChunks.length} chunks with empty content`);
  }

  // Check for chunks with suspiciously low token counts
  const suspiciousChunks = chunks.filter(chunk => 
    chunk.tokenCount !== null && chunk.tokenCount < 5 && chunk.tier >= 2
  );

  if (suspiciousChunks.length > 0) {
    corruptionIssues.push(`${suspiciousChunks.length} chunks with suspiciously low token counts`);
  }

  if (corruptionIssues.length > 0) {
    return {
      status: 'corrupted',
      details: `Data corruption detected: ${corruptionIssues.join(', ')}`,
      recommendations: [
        'Run validation stage to identify and fix corruption',
        'Consider regenerating affected chunks',
        'Check recent processing logs for errors'
      ]
    };
  }

  // 7. Check if outdated
  const oldestChunk = chunks.reduce((oldest, chunk) => 
    chunk.updatedAt < oldest ? chunk.updatedAt : oldest, 
    chunks[0]?.updatedAt || new Date()
  );
  const daysSinceUpdate = (Date.now() - oldestChunk.getTime()) / (1000 * 60 * 60 * 24);
  
  if (daysSinceUpdate > 7) {
    return {
      status: 'outdated',
      details: `Content last updated ${Math.floor(daysSinceUpdate)} days ago`,
      recommendations: [
        'Consider regenerating if source content has changed',
        'Review for relevance to current version',
        'Update if project requirements have evolved'
      ]
    };
  }

  // 8. All checks passed - healthy!
  return {
    status: 'healthy',
    details: `${chunks.length} chunks, ${chunksWithEmbeddings.length} with embeddings, tree structure valid`,
    recommendations: ['No action needed - project is healthy']
  };
}

export async function GET(request: NextRequest) {
  try {
    // Check authentication
    const session = await getSession();
    if (!session?.user || (session.user as any)?.role !== 'admin') {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      );
    }

    // Use the new SemanticHealthMonitor for comprehensive metrics
    const healthMonitor = getSemanticHealthMonitor();
    const healthMetrics = await healthMonitor.performHealthCheck({
      includePerformanceTests: false, // Skip performance tests for faster response
      includeCostAnalysis: true,
      includeDataValidation: true
    });

    // Legacy metrics for backward compatibility
    const totalChunks = healthMetrics.database.totalChunks;
    const chunksWithEmbeddings = healthMetrics.database.chunksWithEmbeddings;

    // Get total projects with semantic indexes
    const totalProjects = await prisma.project.count();
    const projectsWithChunks = await prisma.contextChunk.groupBy({
      by: ['projectIndexId'],
      _count: true
    });

    // Calculate average query time (mock for now - would need actual query logs)
    const averageQueryTime = 45; // ms

    // Get index size estimate
    const indexSizeBytes = totalChunks * 1536 * 4; // Approximate: chunks * dimensions * 4 bytes per float
    const indexSizeMB = (indexSizeBytes / (1024 * 1024)).toFixed(2);

    // Fetch project semantic status
    const projects = await prisma.project.findMany({
      select: {
        id: true,
        title: true,
        updatedAt: true
      },
      orderBy: { updatedAt: 'desc' }
    });

    const projectStatus = await Promise.all(
      projects.map(async (project) => {
        // Get chunks for this project with detailed information
        const chunks = await prisma.contextChunk.findMany({
          where: { projectIndexId: project.id },
          select: {
            id: true,
            tier: true,
            chunkId: true,
            title: true,
            content: true,
            tokenCount: true,
            parentChunkId: true,
            rootChunkId: true,
            embeddingGeneratedAt: true,
            updatedAt: true,
            metadata: true
          }
        });

        const chunkCount = chunks.length;
        const tierDistribution = chunks.reduce((acc, chunk) => {
          acc[chunk.tier] = (acc[chunk.tier] || 0) + 1;
          return acc;
        }, {} as Record<number, number>);

        // Analyze project health in detail
        const healthAnalysis = await analyzeProjectHealth(project, chunks);
        
        // Get total cost for this project
        const operations = await prisma.semanticOperation.findMany({
          where: { 
            projectId: project.id,
            success: true
          },
          select: { cost: true }
        });
        const totalCost = operations.reduce((sum, op) => sum + Number(op.cost), 0);

        // Get last regeneration time
        const lastRegeneration = await prisma.semanticOperation.findFirst({
          where: {
            projectId: project.id,
            operationType: 'regeneration',
            success: true
          },
          orderBy: { completedAt: 'desc' },
          select: { completedAt: true }
        });

        return {
          projectId: project.id,
          title: project.title,
          chunkCount,
          tierDistribution,
          lastRegenerated: lastRegeneration?.completedAt || project.updatedAt,
          totalCost,
          healthStatus: healthAnalysis.status,
          healthDetails: healthAnalysis.details,
          healthRecommendations: healthAnalysis.recommendations
        };
      })
    );

    // Get budget status
    const budgetStatus = await semanticBudgetManager.getActiveBudget();

    // Get cost analytics
    const costBreakdown = await semanticBudgetManager.getCostBreakdown();

    // Get batch job status (placeholder - would integrate with actual batch service)
    const batchJobs = await prisma.semanticOperation.findMany({
      where: {
        operationType: 'embedding',
        metadata: {
          path: ['batchMode'],
          equals: true
        }
      },
      orderBy: { startedAt: 'desc' },
      take: 10,
      select: {
        id: true,
        projectId: true,
        startedAt: true,
        completedAt: true,
        success: true,
        chunksProcessed: true,
        cost: true,
        metadata: true
      }
    });

    const batchJobStatus = batchJobs.map(job => ({
      id: job.id,
      projectId: job.projectId,
      status: job.completedAt 
        ? (job.success ? 'completed' : 'failed')
        : 'in_progress',
      startedAt: job.startedAt,
      completedAt: job.completedAt,
      chunksProcessed: job.chunksProcessed,
      cost: Number(job.cost),
      estimatedSavings: Number(job.cost) * 0.5, // 50% savings with batch mode
      progress: job.metadata && typeof job.metadata === 'object' && 'progress' in job.metadata
        ? (job.metadata as any).progress
        : 100
    }));

    // Construct dashboard metrics
    const dashboardMetrics = {
      vectorIndexHealth: {
        totalProjects,
        indexedProjects: projectsWithChunks.length,
        totalChunks,
        totalEmbeddings: chunksWithEmbeddings,
        averageQueryTime,
        indexSize: `${indexSizeMB} MB`
      },
      budgetStatus: {
        allocated: budgetStatus.allocatedFunds,
        remaining: budgetStatus.remainingFunds,
        percentUsed: budgetStatus.percentUsed * 100,
        warningLevel: budgetStatus.warningLevel
      },
      projectStatus,
      costAnalytics: {
        totalSpent: budgetStatus.totalSpent,
        breakdown: costBreakdown
      },
      batchJobStatus
    };

    return NextResponse.json(dashboardMetrics);
  } catch (error) {
    console.error('Error fetching semantic dashboard metrics:', error);
    return NextResponse.json(
      { error: 'Failed to fetch dashboard metrics' },
      { status: 500 }
    );
  }
}
